packages:
  - apps/*
  - '!**/demo/*'
  - '!**/test/*'
onlyBuiltDependencies:
  - '@rolldown/browser'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - core-js
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
