export const defaultImportMap = {
    imports: {
        react: "https://esm.sh/react@18.3.1",
        "react/": "https://esm.sh/react@18.3.1/",
        "react-dom": "https://esm.sh/react-dom@18.3.1",
        "react-dom/": "https://esm.sh/react-dom@18.3.1/",
        lodash: "https://esm.sh/lodash@4.17.21/es2022/lodash.min.mjs",
        "lodash/": "https://esm.sh/lodash@4.17.21/",
        mathjs: "https://esm.sh/mathjs@14.5.2/es2022/mathjs.mjs",
        "prop-types": "https://cdn.jsdelivr.net/npm/prop-types@15.8.1/prop-types.min.js",
        three: "https://cdn.jsdelivr.net/npm/three@0.177.0/build/three.module.js",
        tone: "./cdn/tone.js",
        "chart.js": "./cdn/chart.js",
        xlsx: "./cdn/xlsx.js",
        papaparse: "./cdn/papaparse.js",
        d3: "./cdn/d3.js",
        mermaid: "./cdn/mermaid.js",
        plotly: "./cdn/plotly.js",
        "plotly.js-dist-min": "./cdn/plotly.js",
        recharts: "./cdn/recharts.js",
        "unocss-browser": "./cdn/unocss.js",
        "lucide-react": "./cdn/lucide-react.js",
        motion: "./cdn/motion.js",
        "framer-motion": "./cdn/motion.js",
    },
};
