export const defaultImportMap = {
    imports: {
        react: "https://esm.sh/react@18.3.1",
        "react/": "https://esm.sh/react@18.3.1/",
        "react-dom": "https://esm.sh/react-dom@18.3.1",
        "react-dom/": "https://esm.sh/react-dom@18.3.1/",
        lodash: "https://esm.sh/lodash@4.17.21/es2022/lodash.min.mjs",
        "lodash/": "https://esm.sh/lodash@4.17.21/",
        mathjs: "https://esm.sh/mathjs@14.5.2/es2022/mathjs.mjs",
        "prop-types": "https://cdn.jsdelivr.net/npm/prop-types@15.8.1/prop-types.min.js",
        three: "https://cdn.jsdelivr.net/npm/three@0.177.0/build/three.module.js",
        p5: "https://cdn.jsdelivr.net/npm/p5@2.0.3/lib/p5.esm.min.js",
        "@react-three/fiber": "https://cdn.jsdelivr.net/npm/@react-three/fiber@9.1.2/dist/react-three-fiber.esm.js",
        "react-use-measure": "https://cdn.jsdelivr.net/npm/react-use-measure@2.1.7/dist/index.js",
        "its-fine": "https://cdn.jsdelivr.net/npm/its-fine@2.0.0/dist/index.min.js",
        scheduler: "https://esm.sh/scheduler@0.23.2",
        "suspend-react": "https://cdn.jsdelivr.net/npm/suspend-react@0.1.3/index.js",
        "react-reconciler": "https://esm.sh/react-reconciler@0.29.2",
        "react-reconciler/constants": "https://esm.sh/react-reconciler@0.29.2/constants",
        zustand: "https://esm.sh/zustand@4.5.7?deps=react@18.3.1",
        "zustand/traditional": "https://esm.sh/zustand@4.5.7/traditional?deps=react@18.3.1",
        tone: "./cdn/tone.js",
        "chart.js": "./cdn/chart.js",
        xlsx: "./cdn/xlsx.js",
        papaparse: "./cdn/papaparse.js",
        d3: "./cdn/d3.js",
        mermaid: "./cdn/mermaid.js",
        plotly: "./cdn/plotly.js",
        "plotly.js-dist-min": "./cdn/plotly.js",
        recharts: "./cdn/recharts.js",
        "unocss-browser": "./cdn/unocss.js",
        "lucide-react": "./cdn/lucide-react.js",
        motion: "./cdn/motion.js",
        "framer-motion": "./cdn/motion.js",
    },
};
